name: Publish Fat Jar To Github Package Repository

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew build -Pversion=${{github.ref}}
      - name: Publish to Github Package Repository
        run: ./gradlew publish -Pversion=${{github.ref}} -Pgithub.token=${{ secrets.GITHUB_TOKEN }}
